docs/src/components/Footer/AvatarList.astro
=> docs: add squashed commit co-authors to footer avatar

pyproject.toml
Better metadata for PyPI, see: https://github.com/manzt/anywidget/pull/32#issuecomment-1402461798
=> chore: actually fix the license for PyPI

.github/workflows/ci.yml, package-lock.json
Separates linting/formatting checks from unittests and makes sure that we can build package every CI. The release action is appended to `Build` when a tagged commit is seen.
=> refactor: CI scripts

docs/src/pages/en/getting-started.mdx, pyproject.toml
=> docs: fix typo

README.md, docs/src/pages/en/getting-started.mdx, pyproject.toml, src/anywidget/_file_contents.py
=> feat: add watchfiles import error message

docs/src/components/examples/Counter.astro
=> docs: update counter mini demo

.changeset/large-bulldogs-matter.md, packages/anywidget/package.json, pnpm-lock.yaml
=> fix: flexible resolution of @jupyter-widgets/base

.changeset/metal-llamas-roll.md, packages/anywidget/src/widget.js
=> feat: log and re-raise error on ESM import failure

docs/src/pages/en/bundling.md
Hi, I was rereading this article and noticed some minor errors. So here are my edit suggestions.
=> Fix some typos in bundling.md

.changeset/clever-ladybugs-float.md, packages/vite/index.js
- fix(vite): support new render context
- changeset
=> fix(vite): support new render context

.changeset/cool-mails-work.md, packages/vite/index.js
- feat(vite): refresh multiple contexts
- changeset
=> fix(vite): support HMR refresh for multiple contexts

.github/workflows/ci-js.yml, .github/workflows/ci.yml, package.json, packages/anywidget/package.json, packages/anywidget/src/index.js, packages/anywidget/src/plugin.js, packages/anywidget/src/widget.js, packages/anywidget/tsconfig.json, packages/types/index.test.ts, packages/types/package.json, packages/types/tsconfig.json, pnpm-lock.yaml, tsconfig.json, vitest.workspace.js
- feat(types): add testing framework
- feat(anywidget): typecheck
- chore: update workflows
=> ci: typecheck and execute unit tests for JS

.changeset/bright-cycles-boil.md, .github/workflows/ci.yml, anywidget/_protocols.py, anywidget/_version.py, packages/anywidget/package.json, pnpm-lock.yaml, pyproject.toml
Think I'm doing this right, lol cc: @tlambert03. Next release will be a minor release.
- feat: Drop support for Python 3.7
- chore: update build-system to use jlab v4
=> feat!: Drop support for Python 3.7

.changeset/hot-emus-look.md, packages/create-anywidget/index.js, packages/create-anywidget/template-vanilla-deno-jsdoc/README.md, packages/create-anywidget/template-vanilla-deno-jsdoc/_gitignore, packages/create-anywidget/template-vanilla-deno-jsdoc/deno.json, packages/create-anywidget/template-vanilla-deno-jsdoc/pyproject.toml, packages/create-anywidget/template-vanilla-deno-jsdoc/src/my_widget/__init__.py, packages/create-anywidget/template-vanilla-deno-jsdoc/src/my_widget/styles.css, packages/create-anywidget/template-vanilla-deno-jsdoc/src/my_widget/widget.js
- feat: add JSDoc Deno template
- formatting
- changeset
=> feat(create-anywidget): add JSDoc TypeScript template (Deno)

.changeset/cyan-wombats-suffer.md, packages/create-anywidget/index.js, packages/create-anywidget/template-vanilla-deno-jsdoc/_gitignore, packages/create-anywidget/template-vanilla-deno-jsdoc/pyproject.toml
- fix(create-anywidget): check-in JS for non-npm template
- changeset
=> fix(create-anywidget): check-in JS for non-npm template

.changeset/short-weeks-care.md, packages/create-anywidget/template-react/js/package.json, packages/create-anywidget/template-vanilla-ts/js/package.json
=> fix(create-anywidget): correct @anywidget/* versions in templates

CONTRIBUTING.md, README.md, docs/package.json, docs/scripts/ipynb.mjs, docs/src/components/Header/Search.tsx, docs/src/consts.ts, docs/src/pages/blog/anywidget-02.md, docs/src/pages/en/bundling.md, docs/src/pages/en/experimental.md, docs/src/pages/en/jupyter-widgets-the-good-parts.md, dprint.json, package.json, packages/anywidget/__tests__/widget.test.ts, packages/anywidget/src/widget.js, packages/create-anywidget/__tests__/index.test.js, packages/create-anywidget/create.js, packages/create-anywidget/index.js, packages/svelte/README.md, packages/types/index.test-d.ts, packages/types/index.ts, packages/vite/README.md, pnpm-lock.yaml, pnpm-workspace.yaml
- chore: replace prettier with dprint
- cleanup
=> chore: Replace prettier with dprint

.changeset/neat-hats-taste.md, packages/deno/mod.ts
Fixes #322
Temporary workaround until we can detect the version of anywidget that has been installed.
=> fix(deno): Use current anywidget version for comms open message

packages/deno/mod.ts
Deno does a `Symbol.for("Jupyter.display") in obj` check now instead of directly trying to get the property. This PR adds a `has` to the model proxy so that Deno will be able to display it directly (either as a result or in `Deno.jupyter.display`).
=> allow Deno to check if display `in` widget

README.md
Fixes #400
Thanks @maartenbreddels :)
=> chore: Fix Discord link

.changeset/real-knives-drive.md, packages/create-anywidget/index.js
- feat(create-anywidget): Update template names
- formatting
=> feat(create-anywidget): Rename template options with additional hints

.changeset/afraid-panthers-explain.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/create.js
This pr is adding readme = "README.md" 
This way e.g.
will become
=> feat(create-anywidget): Add "readme" to pyproject.toml template

.changeset/shy-spies-drum.md, anywidget/_descriptor.py, anywidget/experimental.py, tests/test_experimental.py
=> feat(anywidget): add dataclass decorator

packages/svelte/README.md
Svelte enthusiasts might stumble across this project and I want to keep aware of the plan. My hope is to use [Runes](https://svelte.dev/blog/runes) for the model because that seems like the way forward for Svelte. It will also make using the model _feel_ very svelty:
```svelte
<script>
export let model; // created by @anywidget/svelte
let doubled = $derived(model.value * 2);
$effect(() => {
console.log("value changed", model.value)
});
</script>
<button onclick={() => model.value++}>Clicked {model.value} times</button>
```
=> chore(svelte): Mention Svelte 5 plan

anywidget.json
This file came from the template and has no use that I can tell.
=> chore: remove anywidget.json

.changeset/eleven-readers-wash.md, packages/create-anywidget/index.js
=> Change order of "Next steps" in create-anywidget

.changeset/moody-insects-clap.md, packages/deno/README.md, packages/deno/mod.ts
=> feat(deno): Un-asyncify `widget` helper

.github/workflows/jsr.yml, .github/workflows/release.yml
- **rm package.json before publishing**
- **switch to macOS release**
=> ci: Switch to macos-14 for release

docs/astro.config.js, docs/package.json, docs/scripts/ipynb.mjs, docs/scripts/utils.mjs, docs/src/components/CodeHero.astro, docs/src/components/HeadSEO.astro, docs/src/components/RightSidebar/TableOfContents.tsx, pnpm-lock.yaml
- **upgrade astro**
- **fix typing**
=> docs: Upgrade Astro (and deps)

docs/astro.config.js, docs/package.json, docs/public/robots.txt, docs/src/components/HeadCommon.astro, pnpm-lock.yaml
=> docs: Add sitemap

docs/astro.config.js, docs/src/components/GitHubCard.astro, docs/src/pages/blog/introducing-anywidget.mdx, docs/src/pages/en/community.mdx, docs/src/pages/en/getting-started.mdx, docs/src/pages/en/jupyter-widgets-the-good-parts.mdx
- **docs: use automatic image op in markdown**
- **feat: optimize gallery**
=> docs: optimize gallery images

docs/src/pages/en/community.mdx
Makes it so that searching for "Gallery" will link to gallery
=> docs: use Gallery so it is searchable

.changeset/breezy-parrots-help.md, anywidget.json
A woefully undocumented, rough edge to widgets....
Fixes #532 #550
=> fix(anywidget): Bring back anywidget.json for notebook v6

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/jsr.yml, .github/workflows/release.yml, anywidget/_descriptor.py, pyproject.toml
https://scientific-python.github.io/repo-review/?repo=manzt%2Fanywidget&branch=main
=> chore: Apply changes from repo-review

anywidget/__init__.py, anywidget/experimental.py, anywidget/widget.py, pyproject.toml, tests/test_widget.py
more simple config with new options
=> chore: Update ruff config

anywidget/_descriptor.py, anywidget/_version.py, anywidget/experimental.py, anywidget/widget.py, pyproject.toml
More suggestions from [scientific-python/repo-review](https://github.com/scientific-python/repo-review)
=> chore: Increase mypy strictness

docs/src/pages/en/jupyter-widgets-the-good-parts.mdx, docs/src/styles/index.css
=> docs: Add data types documentation

.changeset/smart-insects-join.md, packages/anywidget/src/widget.js
=> chore: Improve ESM deprecation notice info

docs/src/pages/en/getting-started.mdx
Small docs change to mention that `anywidget` is supported in marimo :)
=> Update getting-started.mdx to include marimo

README.md
@akshayka ok to add here as well, with link?
=> Add marimo to readme

docs/src/components/IntegrationsGallery.astro, docs/src/pages/en/community.mdx
=> docs: Add integrations section

docs/src/pages/en/notebooks/counter.ipynb
=> docs: Update counter example with install for Google Colab

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: Add issue templates

docs/src/pages/en/getting-started.mdx
=> docs: Clean up transition to HMR in getting started

anywidget/__init__.py, anywidget/_cellmagic.py, anywidget/_descriptor.py, anywidget/_file_contents.py, anywidget/_protocols.py, anywidget/_util.py, anywidget/experimental.py, anywidget/widget.py, pyproject.toml, tests/test_cellmagic.py, tests/test_descriptor.py, tests/test_experimental.py, tests/test_file_contents.py, tests/test_protocols.py, tests/test_utils.py, tests/test_widget.py
Ruff is adding new rules frequently, and I'd prefer to opt out rather opt in.
=> chore: Select ALL Ruff rules

docs/src/components/Header/LanguageSelect.tsx, docs/src/components/Header/Search.tsx, docs/src/components/Header/ThemeToggleButton.css, docs/src/styles/index.css, docs/src/styles/theme.css, package.json, pnpm-lock.yaml
- **chore: Update biome**
- **chore: Add missing svg titles**
=> chore: Upgrade biomejs

.changeset/brown-cougars-cover.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/create.js
- **Add PEP 735 dependency groups with instructions for how to use uv**
- **Add changeset**
- **fix: Add project field**
- **Update instructions**
- **update readme**
=> feat(create-anywidget): Recommend uv for project template

.changeset/dry-jobs-know.md, packages/deno/deno.json, packages/deno/deno.lock, packages/deno/src/mod.ts, packages/deno/src/utilities.ts, packages/deno/test.ts
=> feat(deno): Support dispatching binary data through the comm

.github/workflows/ci.yml, .github/workflows/release.yml, anywidget/_file_contents.py, pyproject.toml, uv.lock
- **Upgrade uv and test py 3.13**
- **Use dependency-groups**
=> Upgrade uv and test py3.13

README.md, anywidget/_descriptor.py, anywidget/widget.py, docs/astro.config.js, docs/src/components/Footer/AvatarList.astro, docs/src/pages/blog/a-year-with-anywidget.md, docs/src/pages/blog/anywidget-02.md, docs/src/pages/blog/introducing-anywidget.mdx, docs/src/pages/en/community.mdx, docs/src/pages/en/getting-started.mdx, docs/src/pages/en/jupyter-widgets-the-good-parts.mdx, packages/anywidget/CHANGELOG.md, packages/anywidget/scripts/jlab.config.cjs, packages/react/index.js, packages/signals/mod.ts, packages/vite/CHANGELOG.md
Would be good to setup a codespell pre-commit, but just do a run by hand for now.
```
codespell --version
2.4.1
```
=> chore: codespell

packages/create-anywidget/package.json, packages/react/package.json, packages/svelte/package.json, packages/types/package.json, packages/vite/package.json, packages/vue/package.json, tsconfig.json
Also adds license metadata to package.json for npm.
=> Add `@anywidget/vue` bridge to project references
