manzt/anywidget

README.md
I have added anywidget to conda-forge. This PR adds instructions for installing anywidget using conda.
https://anaconda.org/conda-forge/anywidget
@manzt Would you be willing to be listed as a maintainer of the conda-forge recipe? There is minimal maintenance work we need to do. Most of the time the repo can do auto merge using the bot. If the dependencies of the package change, then we need to submit a PR to update the recipe. 
https://github.com/conda-forge/anywidget-feedstock
=> feat: Add conda installation instructions

.gitattributes
The [linguist](https://github.com/github/linguist/blob/master/docs/overrides.md#documentation) breakdown for the repo might give the impression that **anywidget** is a JavaScript library. This PR tells linguist to treat some JS files as vendored (i.e., some boilerplate and the vite plugin), so that the language breakdown is a better reflection of the project.
Now,
```bash
❯ github-linguist -b
61.76%  5064       Python
38.24%  3136       JavaScript
Python:
anywidget/__init__.py
anywidget/_version.py
anywidget/widget.py
setup.py
tests/test_widget.py
JavaScript:
src/widget.js
```
=> chore: add .gitattributes for linguist

docs/src/consts.ts, docs/src/env.d.ts
**anywidget** was accepted for [DocSearch program](https://docsearch.algolia.com/docs/docsearch-program/)! This PR enables their search on the website. It's appears that it's fine to keep the Algolia API keys in the repo (Astro and Vite both do this).
=> docs: enable DocSearch

anywidget/__init__.py, anywidget/widget.py, tests/test_colab.py
Fixes #48
Dynamically adds `_ipython_display_` method to an instance of `anywidget.widget.AnyWidget` if both:
1. detect we are in a Google Colab and 
2. `_ipython_display_` is not already implemented
Importantly, this PR changes the previous behavior of calling `google.colab.outputs.enable_custom_widget_manager()` to within the `anywidget.AnyWidget` constructor. From my experimenting, there seems to be no issue with executing this function each time we create a new instance. ~I think ideally we call this enable function only the _first_ time we detect a widget instance in a colab. Maybe some state that lives on the class?~
EDIT: The enable_custom_widgets_manager is now only excuted once. Originally I had a `functools.cache` init function, but didn't realize that wasn't available in older …
=> fix: dynamically set _ipython_display_ for widgets in Google Colab

.gitattributes
Reverts #36
**anywidget** is undoubtably a Python project now and we don't need to try to game GitHub's metadata.
=> chore: remove gitattributes for linguist

anywidget/_descriptor.py, src/widget.js, tests/test_descriptor.py
Right now "best-in-class" widget development is only enabled when developers setup Vite and use its HMR. However, it's kind of annoying to setup Vite with **anywidget** and get the [two playing together](https://anywidget.dev/en/bundling/). 
This PR is an experiment to enable granular HMR  updates _within_ **anywidget** and be agnostic to bundlers or dev-servers. The trick is that we can send messages to an `AnyModel` any time the front-end code is updated, and then clear existing views and re-render the model. This means we could build adapters on the python side for various JS setups.
https://user-images.githubusercontent.com/24403730/217332349-eec5e4c2-1004-4cef-aff5-995a6f936bae.mov
```python
from anywidget._descriptor import MimeBundleDescriptor
from psygnal import evented
from …
```
=> feat: native HMR

.github/workflows/ci.yml, anywidget/_file_contents.py, pyproject.toml, tests/test_file_contents.py
Closes #61
This PR adds the `anywidget._file_contents.FileContents` object. `FileContents` watches for file changes in a provided path in a background thread and continuously emits `changed` signals any time the file changes, until the file is deleted (emits a `deleted` event). Connecting `FileContents` with `MimeReprBuilder` or `AnyWidget` allows for #60 to be leveraged during development. Currently this must be done manually, but we should aim to make the creation of `FileContents` hidden.
```python
from anywidget._file_contents import FileContents
contents = FileContents("index.js")
class Counter(anywidget.AnyWidget):
_esm = str(contents)
value = traitlets.Int(0).tag(sync=True)
counter = Counter()
contents.changed.connect(lambda change: counter._esm = …
```
=> feat: add `FileContents` to read/watch files

anywidget/widget.py, src/widget.js, tests/test_widget.py
Requires users to specify `_esm` instead of the legacy `_module`, for their widget JavaScript code. We previously supported both, but I don't think this is necessary at v0.1 our docs only use `_esm` so the legacy syntax is very hidden.
=> chore: deprecate _module in favor of _esm

.changeset/config.json, .changeset/cyan-suits-share.md, .changeset/fluffy-oranges-begin.md, .changeset/friendly-rocks-rush.md, .changeset/good-shrimps-complain.md, .changeset/red-dingos-hammer.md, .changeset/swift-wasps-brake.md, .changeset/two-goats-hammer.md, .changeset/unlucky-scissors-taste.md, .github/workflows/ci.yml, README.md, package-lock.json, package.json
Introduces the [`changesets`](https://github.com/changesets/changesets) workflow. It lets contributors declare how their changes should be released, and then we automate updating changelogs and publishing new versions of `anywidget` in CI.
Additionally, this PR adds the `@changesets/cli` as a dependency to write `changsets` files. The recommended flow is to:
- create a PR
- run `npx changeset`
- pick `patch`/`minor`/`major` intent
- write a descriptive message (maybe code example) documenting the change
- check-in the `changeset` created in `.changesets/`
When it's time to make a release all the `.changesets/*` are collected in our CI and 1.) a version is decided on based on the set of changes and 2.) changelogs are added to the release from the change files.
> **Note**: we technically …
=> chore: use changesets for versioning and publishing

.changeset/yellow-bees-refuse.md, anywidget/_descriptor.py, anywidget/_util.py, anywidget/widget.py, tests/test_descriptor.py, tests/test_utils.py, tests/test_widget.py
Implements the more robust solution for supporting colab outlined in #63, but also for `ReprMimeBundle`.
=> feat: inject colab meta in `_repr_mimebundle_`

.changeset/giant-pets-eat.md, src/widget.js
anwidget doesn't currently expose an API for defining custom cleanup logic for a view. Typically, one would define this logic with `DOMWidgetView.remove()` so anywidget users _could_ mutate the `view` instance within `render` to achieve this behavior:
```javascript
export function render(view) {
/* create dom elements and setup subscribers */
let originalRemove = view.remove;
view.remove = () => {
/* cleanup event listeners/resources */
originalRemove();
}
}
```
but 1.) this requires some boilerplate to do correctly and 2.) we can't call `remove()` for hot reloading because it removes `view.el` from the DOM. 
So, some way we need users to be able to define custom cleanup for whatever they've setup in `render`. I think this lends itself nicely to a `React.useEffect`-like API, where …
=> feat: add (optional) unmount return to render

.changeset/green-queens-beam.md, anywidget/_descriptor.py, anywidget/_util.py, anywidget/widget.py, tests/test_descriptor.py, tests/test_utils.py, tests/test_widget.py
This PR adds a useful feature to auto-create `FileContents` objects from `_esm` or `_css` attributes on anywidget subclasses.
```python
class Counter(anywidget.AnyWidget):
_esm = "index.js"
value = traitlets.Int().tag(sync=True)
Counter()
```
A `FileContents` object is only created if the provided `str` or `pathlib.Path` points to an existing file. In addition, the object is set to "watch mode" (spinning up a background thread) if the path is detected outside of `site-packages` (i.e., likely a development install).
EDIT:
This PR now also implements supports detection in the descriptor:
```python
from anywidget._descriptor import MimeBundleDescriptor
from psygnal import evented
from dataclasses import dataclass
@evented
@dataclass
class Counter: …
```
=> feat: auto infer `FileContents` for valid file paths

packages/anywidget/src/widget.js
There is currently a variable scoping issue in v0.2.2 resulting in the following JS error:
```
Uncaught (in promise) ReferenceError: widget is not defined
```
https://observablehq.com/d/d283036191b4763e
=> Fix JS variable scope issue

.changeset/great-trainers-fetch.md, README.md, docs/src/pages/blog/anywidget-02.md, docs/src/pages/en/getting-started.mdx, pyproject.toml
Right now, we raise an exception if one starts developing a widget locally but doesn't have `watchfiles` installed.
Requiring developers to remember to install optional dev dependencies (i.e.,`pip install "anywidget[dev]"`) is kind of annoying, and it's a pretty minimal dependency. This PR adds `watchfiles` as a direct dependency so developers can use `pip install anywidget` and get started without any hiccups.
As an alternative, we could add a warning rather rather than raising an exception, notifying the developer that "watchfiles" must be installed to enable anywidget's live development features, but still load the file the first time. I think adding the dependency is more simple solution, but am open to alternatives.
=> fix: add watchfiles as dependency

.changeset/itchy-dolphins-kick.md, anywidget/_descriptor.py, pyproject.toml
CI is failing in #118 because `ipykernel.comm.Comm` is deprecated.
=> fix: replace deprecated ipykernel.comm.Comm

.changeset/pretty-rockets-behave.md, anywidget/experimental.py, examples/minimal_example.ipynb, tests/test_experimental.py
Adds the `anywidget.experimental` model with a simple decorator implementation.
```python
import dataclasses
import psygnal
from anywidget.experimental import widget
@widget(esm="index.js")
@psygnal.evented
@dataclasses.dataclass
class Counter:
value: int = 0
```
```python
import msgspec
import psygnal
from anywidget.experimental import widget
@widget(esm="index.js")
@psygnal.evented
class Counter(msgspec.Struct, weakref=True):
value: int = 0
```
```python
from psygnal import EventedModel # pydantic
from anywidget.experimental import widget
@widget(esm="index.js")
class Counter(EventedModel):
value: int = 0
```
In a follow-up PR, I'd like to automatically decorate a class with a model and emitter if undecorated. E.g.,
```python
from anywidget.experimental import widget …
```
=> feat: add experimental module with decorator

.changeset/gentle-frogs-pretend.md, anywidget/_descriptor.py, tests/test_descriptor.py
```python
@widget(esm="index.js")
@psygnal.evented
@dataclasses.dataclass
class Counter:
value: int = 0
```
Previously (in IPython):
```python
In [1]: Counter()
```
Now:
```python
In [1]: Counter()
```
=> fix: forward obj __repr__ for plain/text mimetype

.changeset/selfish-kids-grin.md, anywidget/_file_contents.py
=> fix: Specify UTF-8 Encoding in `FileContents.__str__`

.changeset/unlucky-moose-carry.md, docs/src/pages/blog/introducing-anywidget.mdx, docs/src/pages/en/getting-started.mdx, docs/src/pages/en/jupyter-widgets-the-good-parts.md, packages/anywidget/package.json, packages/anywidget/src/widget.js, packages/types/index.d.ts, pnpm-lock.yaml
This PR addresses issue #137 by making changes to object exposed to user-provided `render`. 
Previous:
```javascript
class AnyView {
async render() {
// ...
let cleanup = widget.render(this);
// ...
}
}
```
Proposed:
```javascript
class AnyView {
async render() {
// ...
let cleanup = widget.render({ model: this.model, el: this.el });
// ...
}
}
```
The key focus is on minimizing the API surface area by reducing the exposed fields to the user-provided render function. This change is expected to improve encapsulation and limit the potential for erroneous modifications.
In a review of current projects utilizing anywidget, no evident use-cases were identified that would be adversely affected by this change. It's worth mentioning that there's still a degree of uncertainty about how these …
=> feat: limit view fields exposed to render function

.changeset/moody-games-invite.md, packages/anywidget/src/widget.js, packages/types/index.d.ts, packages/types/package.json, pnpm-lock.yaml
Similar to #138
Proxies access to `AnyModel` to automatically provide the `AnyView` instance as context to `model.on` and `model.off`. This ensures that the event handlers will be properly cleaned up when the view is unmounted by anywidget.
=> feat: restrict access to model within render context

anywidget/_descriptor.py
I'm doubtful that many are using the descriptor API, so this PR deprecates support for pydantic v1. I'm curious if we should try to support v1 still.
cc: @tlambert03 not sure if you have any thoughts here
=> feat(descriptor): support Pydantic v2

docs/src/pages/en/getting-started.mdx
=> docs: Fix typo in getting-started.mdx

.changeset/selfish-dryers-flow.md, packages/anywidget/src/widget.js, packages/types/index.d.ts
Fixes #193. This can be useful for creating container widgets and avoids exposing more backbone/jupyter-widgets internals.
```python
import ipywidgets as ipw
class Box(anywidget.AnyWidget):
_esm = """
async function unpack_models(model_ids, manager) {
return Promise.all(
model_ids.map(id => manager.get_model(id.slice("IPY_MODEL_".length)))
);
}
export async function render({ model, el }) {
let model_ids = model.get("children");
let children_models = await unpack_models(model_ids, model.widget_manager);
for (let model of children_models) {
let child_view = await model.widget_manager.create_view(model);
el.appendChild(child_view.el);
}
}
"""
children = traitlets.List(trait=traitlets.Instance(ipw.DOMWidget)).tag(sync=True, **ipw.widget_serialization) …
```
=> feat(anywidget): expose model.widget_manager

CHANGELOG.md, packages/react/README.md, packages/react/index.js, packages/react/package.json, packages/react/tsconfig.json, pnpm-lock.yaml
Follow up to discussion in https://github.com/Octoframes/anywidget-react-vite-test/pull/1#issuecomment-1642180284.
Adds the `@anywidget/react` package that takes care of some boilerplate to connect Jupyter Widget's backbone models
with React.
Usage (without a bundler):
```python
class Counter(anywidget.AnyWidget):
_esm = """
import * as React from "https://esm.sh/react@18";
import { createRender, useModelState } from "https://esm.sh/@anywidget/react?deps=react@18,react-dom@18";
function Counter() {
let [value, setValue] = useModelState("value");
return React.createElement(
"button",
{ onClick: () => setValue(value + 1) },
`count is ${value}`
);
}
export let render = createRender(Counter);
"""
value = traitlets.Int(0).tag(sync=True)
Counter()
```
Usage …
=> feat: add @anywidget/react package

.changeset/lazy-trees-yawn.md, packages/react/index.js
Adds a hook to grab the model. Can be useful to subscribe to custom messages:
```javascript
import * as React from "react";
import { createRender, useModel } from "@anywidget/react";
export let render = createRender(() => {
let model = useModel();
let [data, setData] = React.useState(null);
React.useEffect(() => {
let callback = (msg) => setData(msg);
model.on("msg:custom", callback);
return () => model.off("msg:custom", callback);
}, [model]);
if (!data) return null;
return <pre>JSON.stringify(data)</pre>;
});
```
=> feat(react): add `useModel` hook

packages/react/package.json, packages/react/tsconfig.json, packages/svelte/README.md, packages/svelte/index.js, packages/svelte/package.json, packages/svelte/tsconfig.json, pnpm-lock.yaml
Towards #202 
Proof of concept, inspired by https://github.com/xnought/svelte-store-anywidget.
Not sure my `onDestroy` behavior will clean things up correctly. Maybe we could keep WeakMap/WeakSet to keep track of stores without requiring users to explicitly cleanup. Thinking the Proxy stuff might be a little too much magic, but I like the restructuring API (you get autocomplete with typescript).
Usage:
```svelte
<script>
import { stores } from "@anywidget/svelte";
const { count } = stores;
</script>
<button on:click={() => $count += 1}Count is {$count}</button>
```
```js
import { createRender } from "@anywidget/svelte";
import Counter from "./Counter.svelte";
export const render = createRender(Counter);
```
The `Stores` also is generic over a Model object for those using TypeScript. I …
=> feat: add `@anywidget/svelte` adapter

packages/create-anywidget/create.js, packages/create-anywidget/index.js
Follow up from https://github.com/Octoframes/anywidget-minimal-react-template/issues/3
In the old version of create-anywidget, copying template files  and then renaming them in the target dir was breaking the git repo.
With this new approach "Read, save to json, modify json, write to the file system", this error does not occur any more
Tested this via:
mkdir hi && cd hi && git init && touch hello.py && echo 'print("hello")' > hello.py
git add . && git commit -m "first file"
node /Users/jan-hendrik/projects/anywidget/packages/create-anywidget/index.js hi
and that works now!
=> Making create-anywidget bulletprooved

.changeset/hot-dingos-taste.md, packages/create-anywidget/template-react-ts/package.json, packages/create-anywidget/template-react-ts/src/my_widget/__init__.py, packages/create-anywidget/template-react/package.json, packages/create-anywidget/template-react/src/my_widget/__init__.py, packages/create-anywidget/template-vanilla-ts/package.json, packages/create-anywidget/template-vanilla-ts/src/my_widget/__init__.py, packages/create-anywidget/template-vanilla/package.json, packages/create-anywidget/template-vanilla/src/my_widget/__init__.py
=> feat(create-anywidget): use `static` folder for JS build assets

packages/create-anywidget/create.js
We store template dependencies in `create-anywidget/package.json` within `devDependencies` to leverage pnpm and dependabot for version updates. The `create.js` script sources versions from this file when writing the project template `package.json`.
While this setup works in production, local workspace packages (e.g., 	@anywidget/react) are labeled as workspace:* during local script testing. This complicates local template trials. This PR addresses and simulates the production behavior for such cases.
=> chore(create-anywidget): find workspace deps when local dev

packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/create.js
For convenience.
I always include .venv in my global gitignore. However, I discovered that "hatch build" requires .venv to also be in the project's gitignore. If not, .venv will be uploaded to PyPI. I experienced this issue firsthand; it took a long time to upload, and it was a challenge to identify the reason for the large package size!
=> Add .venv to gitignore

.changeset/small-spies-sort.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/__tests__/index.test.js, packages/create-anywidget/create.js, packages/create-anywidget/index.js
Bun is a replacement for Node.js and comes with a built-in package manager and bundler (and test runner!). I think it very well suited as a companion for anywidget projects. I'd like the templates to fully support bun.
This PR detects if the project is running in Node.js or bun by looking at the `globalThis.Bun` and then generates the `build` script in the package.json based on the the environtment:
- Node.js - `esbuild --bundle`
- Bun - `bun bundle`
The difference is that this eliminates a dependency in those templates in favor of the "bun" version.
TODO: I need to figure out how/if the hatchling jupyter builder supports bun.
=> feat(create-anywidget): Support Bun

packages/anywidget/mod.ts
Adds a `mod.ts` for minimal boilerplate for using anywidget frontend from Deno jupyter kernel.
```ts
import { widget } from "https://github.com/manzt/anywidget/mod.ts";
let model = await widget({
// shared model between frontend and backend
state: { value: 0 },
// front-end render function
render: ({ model, el }) => {
let h1 = Object.assign(document.createElement("h1"), {
innerText: "Value is " + model.get("value"),
});
model.on("change:value", () => {
h1.innerText = "Value is " + model.get("value");
});
el.appendChild(h1);
}
});
model
```
```ts
for (let i = 1; i <= 10; i++) {
model.set("value", i);
await new Promise(resolve => setTimeout(resolve, 500));
}
```
=> feat(deno): add experimenal deno mod

packages/anywidget/mod.ts
This is a rough way to include imports, which could be a general preamble instead.
```typescript
import { widget } from "./mod.ts";
let model = await widget({
// shared model between frontend and backend
state: { data: [4, 8, 15, 16, 23, 42] },
imports: `
import * as d3 from "https://esm.sh/d3@7";
`,
// front-end render function 
render: ({ model, el }) => {
const width = 500;
const svg = d3.select(el)
.append("svg")
.attr("width", width)
const x = d3.scaleLinear()
.range([0, width]);
const updateChart = (data) => {
// Update scale domain based on new data
x.domain([0, d3.max(data)!]);
const bars = svg.selectAll("rect")
.data(data);
// Update existing bars
bars
.attr("width", x)
.attr("y", (d, i) => i * 25)
.attr("height", 20);
// Add new bars
bars.enter().append("rect")
.attr("x", 0) …
```
=> accept imports in deno anywidget

packages/deno/mod.ts, packages/deno/test.ts
@rgbkrk also exposes an `_internals` export which you can get access to the `Comm` for the `model` returned from `widget`:
```typescript
import { widget, _internals } from "./mod.ts";
let model = await widget({
state: { value: 0 },
render: () => {},
});
let comm = _internals.get_comm(model);
```
=> test(deno): add `test.ts`

.changeset/hip-pianos-impress.md, packages/deno/mod.ts
Tries to discover the widget version from `share/jupyter/labextension/anywidget/package.json` which is added to the `VIRTUAL_ENV` after running `pip install anywidget`.
=> feat(deno): discover installed anywidget version

packages/deno/README.md
The string split happens later in the example and the promise has to be awaited first.
=> Fix Deno example README.md

.changeset/serious-panthers-battle.md, anywidget/_descriptor.py, tests/test_descriptor.py
This PR introduces an required `include` parameter to `_get_anywidget_state` for selective field serialization. This can help optimize performance by avoiding serializing fields that aren't emitted in events to the front end.
This is a BREAKING change because it requires implementors of `_get_anywidget_state` to
account for `include` in the function signature.
```python
from dataclasses import dataclass, asdict
from io import BytesIO
import polars as pl
import psygnal
@psygnal.evented
@dataclass
class Foo:
value: int
df: pl.DataFrame
def _get_anywidget_state(self, include: set[str] | None):
data = asdict(self)
if include and "df" in include:
with BytesIO() as f:
self.df.write_ipc(f)
data["df"] = f.getvalue()
else:
del data["df"] # don't serialize df to bytes
return data
```
Thoughts, …
=> feat(experimental): Support getting partial state

.changeset/metal-yaks-tickle.md, .changeset/serious-panthers-battle.md, packages/deno/install.ts, packages/deno/jupyter_paths.ts, packages/deno/mod.ts, packages/deno/uninstall.ts
Removes the need to `pip install anywidget` for deno kernels. Can just do it with Deno:
```sh
deno run --allow-net --allow-write ./install.ts
```
TODO: Hmm also need to install `@jupyter-widgets/base`...
=> feat(deno): Add (un)install scripts for front end code

.changeset/shiny-planes-burn.md, anywidget/_util.py, tests/test_utils.py, tests/test_widget.py
Fixes #344. This is kind of more tricky than I'd hoped and has to deal with the overloads for `_esm`:
```python
class Widget(anywidget.AnyWidget):
_esm = "http://localhost:8080/index.js" # a URL
```
```python
class Widget(anywidget.AnyWidget):
_esm = "index.js" # a string for a path
```
```python
class Widget(anywidget.AnyWidget):
_esm = """
export function render({ model, el }) { /* ... */ }
""" # string for the _contents_ of a file
```
```python
class Widget(anywidget.AnyWidget):
_esm = pathlib.Path("index.js") # a pathlib.Path object
```
If we are provided a `pathlib.Path` object, we now assert that the file exists. Otherwise, we will try to "guess"
whether the string is 1.) a URL, 2.) raw file contents, or 3.) a file path.
TL;DR – an explicit `pathlib.Path` will always lead to a …
=> feat(anywidget): Raise Python error when file is missing

README.md
Anywidget is not 1.0, but this warning seems a bit agressive in its current state. Maybe we pick a different warning/phrasing before merging, but the pre-1.0 semver should be a good indicator of stability.
=> chore: Remove stability warning from README

.changeset/five-clocks-tell.md, packages/anywidget/src/widget.js
Fixes #411. This PR addresses an implicit issue due to ipywidget's default serde. Anywidget doesn't allow for custom serializers, but ipywidget's serialization of `layout`/`style` traits seems to have a race condition where `unpack_models` returns a `Promise` that is omitted with the default `JSON.stringify(JSON.parse(...))` trick. 
This mimics the current behavior of ipywidgets, but explicitly the special case where `layout` and `style` are Promises. We do this rather than falling back to JSON.stringify + JSON.parse to that users will see errors if they accidentally do the same.
=> fix(anwidget): Skip `Promise` serialization for ipywidget's `layout`/`style` traits

.changeset/olive-dragons-notice.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/create.js
I've tested all 5 options with 
cd packages/create-anywidget
npm install
node index.js
there was one tricky part:
"from ${name} import Counter\n",
had to be replaced with 
"from ${name} import Counter\\n",
but now everything works fine.
=> feat: Add a example notebook to the cookiecutter

.changeset/shiny-houses-run.md, anywidget/_util.py, anywidget/experimental.py, pyproject.toml, tests/test_descriptor.py, tests/test_utils.py, tests/test_widget.py
Fixes #423 #374 
Makes anywidget's native HMR explicit and opt-in via the `ANYWIDGET_HMR` environment variable. 
The built-in HMR is only meant to be used during "live" development, when _local_ widgets are in imported and used in an active notebook. However, our heuristics for enabling this development feature lead to many false positives, and thus issues  issues in various non- "live" development settings #423, #374, #276.
**This is a bad experience for end users**. 
It doesn't seem possible to account for all these edge cases, and since HMR is meant as a development only feature, it makes sense to make it explicit and opt-in _by the developer_. This PR requires an environment variable to apply anywidget's prior heuristics. It can be set in a notebook:
```python
%env ANYWIDGET_HMR=1
``` …
=> feat(anywidget): Make HMR explicit and opt-in

.changeset/kind-geckos-switch.md, packages/anywidget/src/widget.js
- fix(anywidget): Actually fix layout serialization
- changeset
=> fix: Actually fix `layout` serialization

tests/test_widget.py
Fix a test failure on Python 3.12:
```python
[   68s] =================================== FAILURES ===================================
[   68s] ________________________ test_patched_repr_ipywidget_v8 ________________________
[   68s] 
[   68s] monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fdb6fb4c2f0>
[   68s] 
[   68s]     def test_patched_repr_ipywidget_v8(monkeypatch: pytest.MonkeyPatch):
[   68s]         w = anywidget.AnyWidget()
[   68s]         bundle = w._repr_mimebundle_()
[   68s]         assert bundle[0] and _WIDGET_MIME_TYPE in bundle[0]
[   68s]         assert bundle[1] == {}
[   68s]     
[   68s]         mock = MagicMock()
[   68s]         mock._installed_url = "foo"
[   68s]         monkeypatch.setitem(sys.modules, "google.colab.output", mock)
[   68s]     
[ …
```
=> Fix mock assert

.github/workflows/ci.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> chore: Try out `macos-14` M1 test runners available for open-source

.changeset/clever-houses-float.md, .github/workflows/ci.yml, packages/anywidget/package.json, pnpm-lock.yaml, pyproject.toml, tests/test_utils.py, tests/test_widget.py
Related 
- https://github.com/manzt/anywidget/pull/161
- https://github.com/manzt/anywidget/issues/166
- https://github.com/manzt/anywidget/pull/167
We've tried to keep backward compatibility with Python 3.7, but now it is getting in the way of supporting 3.12. Python 3.7 has been EOL for almost a year, and many others in the ecosystem have moved on (including JupyterLab). If we were able, I'd try to keep support but it's causing too many issues with latest version of Python.
Let me explain. Custom Jupyter Widgets (which anywidget is internally) requires building with JupyterLab (via `@jupyterlab/builder`). In order to build a custom widget, and hence anywidget from scratch the build system must run:
```sh
jupyter labextension build
```
The version of JLab (Python) and …
=> feat!: Add support for Python 3.12 and drop Python 3.7

.github/workflows/ci.yml, package.json, packages/anywidget/package.json, packages/anywidget/scripts/build-lab.cjs, packages/anywidget/scripts/build.mjs, packages/anywidget/src/plugin.js, packages/anywidget/src/widget.js, packages/types/package.json, pnpm-lock.yaml, pyproject.toml
Removes need to have JupyterLab as a part of the build-system. Allows us to keep backward compat with Python 3.7.
=> chore: Drop JupyterLab build dependency

.changeset/flat-donuts-rule.md, packages/types/README.md, packages/types/index.ts
Adds a single type for a default export. The types of `initialize` and `render` are automatically inferred.
```js
/**
* @typedef Model
* @prop {number} value - the current count
*/
/** @type {import("@anywidget/types").AnyWidget<Model>} */
export default {
initialize({ model }) {
let value = model.get("value");
//^? number
},
render({ model, el }) {
let value = model.get("value");
//^? number
model.get("nope");
// type error, `nope` is not defined on Model
model.set("value", "not a number");
//^? type error, must be a number
},
};
```
=> feat: Add AnyWidget type

.changeset/hot-dolphins-grab.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/create.js
I can never remember the [`autoreload`](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) extension, which seems like it would be nice to include by default in the demo notebook. This way you can edit the Python code without needing to restart the kernel.
=> feat(create-anywidget): Add `autoreload` extension to demo notebook

docs/src/pages/en/bundling.md
Small typo, `plugin` -> `plugins`: https://vitejs.dev/config/shared-options.html#plugins
=> fix(docs): Fix typo in vite config

.changeset/pink-impalas-cheat.md, anywidget/experimental.py, tests/test_widget.py
Properties can have unexpected behaviors (if fields are not set). This PR just suppresses exceptions when inspecting for RPC commands.
Suppresses error coming up in jupyter-scatter: https://github.com/flekschas/jupyter-scatter/issues/115. It uncovered a bug in JupyterScatter, but I think we shouldn't just fail if there is a weird property.
=> feat(anywidget): Suppress errors when inspecting for RPC commands

.changeset/ten-apricots-float.md, anywidget/experimental.py, anywidget/widget.py
separates the collection and registration of anywidget commands.  `_collect_anywidget_commands` happens on `__init_subclass__` ... and doesn't require getting any attributes on widget instances.  while `_register_anywidget_commands` still happens on widget init.
just an option. not necessarily much better :)
=> Refactor AnyWidget command registration

.github/workflows/jsr.yml
Hello here!
This prevents the action from being triggered upon fork synchronization
=> CI: add test on repository name

docs/src/pages/blog/anywidget-02.md
Quick sketch of the scenario where you use the cleanup function returned from `render()` to call `cancelAnimationFrame` to break the continuously updating frameloop.
I still want to think about whether this is the most minimal and expressive code example (that's why I'm keeping it a draft). There also might be a better way to word the description.
=> docs: cleanup after requestAnimationFrame example

packages/react/README.md
This PR fixes a typo (`count` variable does not exist) and updates to use the new render export mechanism.
=> Fix typo in React package README

.changeset/three-snails-give.md, packages/anywidget/src/widget.js, packages/types/index.ts
This allows more flexible control over aborting the invoke request, including delegating to third-party libraries that manage cancellation.
```js
export default {
async render({ model, el }) {
const controller = new AbortController();
// Randomly abort the request after 1 second
setTimeout(() => Math.random() < 0.5 && controller.abort(), 1000);
const signal = controller.signal;
model
.invoke("echo", "Hello, world", { signal })
.then((result) => {
el.innerHTML = result;
})
.catch((err) => {
el.innerHTML = `Error: ${err.message}`;
});
},
};
```
=> feat(experimental): Replace invoke timeout with `AbortSignal`

.changeset/empty-walls-know.md, anywidget/experimental.py, pyproject.toml
Fixes #543
Refactor for 0.9.7 changed the API by accident.
=> fix(experimental): Ensure `command` is called with `self`

.changeset/real-jeans-fail.md, anywidget/_descriptor.py, anywidget/_util.py, anywidget/widget.py, tests/test_descriptor.py
Make a blanket `_repr_mimbundle_` implementation
`ipywidgets` v7 and v8 switched from using `_ipython_display_` to `_repr_mimebundle_` for rendering widgets in Jupyter. This means that depending on which version of `ipywidgets` used (v7 in Google Colab), anywidget end users need to handle the behavior of both methods (if they want to wrap the underlying widget in another class). 
This PR adds a blanket implementation of `_repr_mimebundle_` so that it is easier to wrap an `anywidget`:
```python
class Widget(anywidget.AnyWidget):
_esm = "index.js"
_css = "style.css"
value = traitlets.Unicode("Hello, World!").tag(sync=True)
class Wrapper:
def __init__(self):
self._widget = Widget()
def _repr_mimebundle_(self, include=None, exclude=None):
return …
```
=> feat: Provide blanket _repr_mimebundle_ implementation

README.md
I don't think the badges add very much and are mostly visual clutter. GitHub provides this information in the side bar (version, license, citation, etc) anyways. This moves the most important links to the top.
=> chore: Cleaner README.md

.changeset/cuddly-fishes-heal.md, anywidget/_descriptor.py, anywidget/_version.py, anywidget/widget.py, tests/test_utils.py
In relation to the discussion about JupyterHub in https://github.com/manzt/anywidget/issues/385, I've suggested to a few of my users to install anywidget on the server, then install lonboard in the client environment. Lonboard does not pin a version of anywidget, so when a new anywidget version is released, the next install of lonboard will break because the client anywidget version does not exactly match the server anywidget version.
I have reason to believe that using `"~major.minor.*"` works, because pydeck has been doing that for its frontend code for a while, to allow the Python code and JS bindings to be versioned separately (see [1](https://github.com/visgl/deck.gl/blob/9117414ef894b8755e0eff33e7cf503a2137249f/bindings/pydeck/pydeck/frontend_semver.py#L1), …
=> Allow semver-compatible frontend versions

.changeset/serious-months-study.md, anywidget/__init__.py, anywidget/_cellmagic.py, anywidget/_descriptor.py, anywidget/_file_contents.py, anywidget/_util.py, anywidget/experimental.py, anywidget/widget.py, pyproject.toml, tests/test_cellmagic.py, tests/test_file_contents.py
This PR a new experimental cell magic `%%vfile`, designed for prototyping widget ideas within Jupyter notebooks. This is not intended for production use. The goal is to enable nicer syntax highlighting of code and to allow using anywidget's Hot Module Replacement (HMR) entirely from within a notebook.
Previously, anywidget ESM and CSS had to be provided as inline strings or file paths. Notebook development required editing JS/CSS as inline strings, which resulted in losing widget state to see front-end code changes. Anywidget's HMR enables live reloading of front-end code without losing state, but only by monitoring the file system (requring making separate files for the best DX). 
With the new `%%vfile` cell magic, you can prototype entirely from within a a single notebook and enjoy …
=> feat: Add `%%vfile` cell magic

docs/src/pages/en/getting-started.mdx
The property name in the example is `value` instead of `count`.
=> Change the property name from count to value

pyproject.toml
The framework classifiers should make anywidget discoverable within the JLab extension manager.
See [classifiers](https://pypi.org/classifiers/).
=> Add trove classifiers to pyproject.toml

docs/src/pages/en/jupyter-widgets-the-good-parts.mdx
Randomly found this `./` link in docs. On localhost that redirects correctly, but when deployed, the resulting link url is [https://anywidget.dev/en/jupyter-widgets-the-good-parts/community](https://anywidget.dev/en/jupyter-widgets-the-good-parts/community) which 404s.
Seems to be the only occurence.
=> Fix link in jupyter-widgets-the-good-parts.mdx

.changeset/wise-poets-look.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/package.json, packages/react/package.json, pnpm-lock.yaml
Supports both React 18 & 19 as possible peer dependencies in the
`@anywidget/react` module.
=> feat(react): Add support for React 19

docs/src/components/IntegrationsGallery.astro
Added Numerous apps as an integration in progress to the community page under integrations.
=> chore(docs): Add Numerous under integrations on community page

.changeset/cuddly-glasses-sell.md, packages/deno/src/utilities.ts, packages/deno/test.ts
The previous implemention incorrectly serialized buffers:
https://github.com/jupyter-widgets/ipywidgets/blob/main/packages/schema/messages.md#implementing-the-jupyter-widgets-protocol-in-the-kernel-1
=> fix(deno): Change `buffer_paths` from `Array<string>` to `Array<Array<string>>`

.changeset/happy-windows-refuse.md, packages/anywidget/src/widget.js
As I explained in the related issue https://github.com/manzt/anywidget/issues/803, any comm messages sent to the widget before it's model was loaded were lost. This should ensure that those messages are also processed.
Fixes: https://github.com/manzt/anywidget/issues/803.
=> fix: comm messages were lost before model was loaded

.changeset/metal-jokes-shine.md, package.json, packages/anywidget/package.json, pnpm-lock.yaml
Fixes #811
In #670, `@anywidget/types` was inadvertently moved to `devDependencies`
for the `anywidget` npm package, causing it to no longer be installed
for users of `anywidget` and breaking imports from `anywidget/types`.
Since splitting our types into a separate package, we generally
encourage using `@anywidget/types` directly, allowing the
[AFM](https://anywidget.dev/en/afm) spec to be versioned independently
from the Python bindings/runtime. However, we can at least continue to
ship to avoid breaking builds.
=> fix(anywidget): Move `@anywidget/types` from `devDependencies` to `dependencies`

.changeset/ready-bars-double.md, packages/create-anywidget/__tests__/__snapshots__/index.test.js.snap, packages/create-anywidget/create.js
=> fix: use `RenderProps` instead of `RenderContext` in Vanilla TS template

.changeset/sixty-rules-turn.md, packages/anywidget/src/widget.js
Fixes #823
Although now stabilized across all major browsers, it may take some time
for folks to upgrade. In the meantime, we can just have a simple utility
which we can eventually deprecate.
=> fix(anywidget): Use temporary polyfill for `Promise.withResolvers`

.changeset/floppy-otters-share.md, .github/workflows/ci.yml, package.json, packages/anywidget/__tests__/widget.test.ts, packages/anywidget/src/widget.js, patches/@jupyter-widgets__base-manager.patch, patches/@jupyter-widgets__base.patch, pnpm-lock.yaml, tsconfig.json, vitest.workspace.js
Uses the Web `AbortController` API to manage subscribers to the Jupyter
Widgets model. This removes lots of the complexity around managing and
removing subscribers by allowing `AnyModel` and `AnyView` to "abort"
their on subscriptions when removed by ipywidgets.
=> refactor(anywidget): Mange frontend HMR runtimes with web `AbortController`

docs/src/styles/index.css
=> fix: zebra striping in dark mode

packages/anywidget/src/widget.js
This PR updates the HMR `Runtime` to rely on `AbortSignal` for canceling reactive effects and managing widget lifecycle. 
It removes `createResource` in favor of manual `createEffect` coordination with a simplified `Result` type. Also adds a 2-second timeout in the initializer such that awaiting `.ready` will throw with a clear message if never resolves.
=> refactor(hmr): Adopt `AbortSignal` for effect cancellation in `Runtime`

.changeset/bumpy-loops-battle.md, anywidget/_descriptor.py
Resolves a bug in the experimental descriptor API by ensuring the initial widget state is sent during comm setup.
=> Fix descriptor API to send initial state for consistent behavior

.changeset/blue-feet-fall.md, .changeset/sad-yaks-kiss.md, .changeset/slow-emus-kneel.md, packages/react/index.js
Changes `useModelState` to use [`React.useSyncExternalStore`](https://react.dev/reference/react/useSyncExternalStore) instead of `useState` + `useEffect`. The hook was introduced in React 18 and is designed for our exact use case (an external source of truth). It ensures a shared source within the component tree, and consistent behavior during concurrent rendering, avoiding subtle bugs present in `useEffect`-based patterns.
The setter function also now mirrors `useState` behavior more precisely, supporting both direct values and functional updates. Also adds generic type param for `useModel` hook.
=> feat(react): Use `React.useSyncExternalStore` and type `useModel` hook

packages/vue/CHANGELOG.md, packages/vue/LICENSE, packages/vue/README.md, packages/vue/index.js, packages/vue/package.json, packages/vue/tsconfig.json, pnpm-lock.yaml
Hey, awesome project! 🎉
I wanted to create some custom widgets using Vue, and since you already have packages for React and Svelte, I decided to contribute the Vue binding code.
The API of the Vue binding is very similar to the @anywidget/react package. The major difference is that instead of returning a getter-setter pair from `useModelState`, we return a `ShallowRef` which can be mutated directly (eg. `value++`). This is more idiomatic to Vue's reactivity system.
I haven't figured out how to get HMR to work, so for now, you’ll need to restart the kernel for updated JS/CSS files to be picked up. If this can be addressed in a patch release, great! Otherwise, I’ll revisit it in a few days to troubleshoot further.
You can check out a demo of this package on the branch …
=> feat: Vue AFM bridge

.github/workflows/ci.yml, .github/workflows/release.yml, pyproject.toml
Removes the need to have explicit version in CI, and will keep local dev
and CI on the same page.
=> Set `tool.uv.required-version` in `pyproject.toml`

pnpm-workspace.yaml
This setting allows the checking of the state of dependencies before
running scripts. The check runs on `pnpm run` and `pnpm exec` commands,
automatically running install if `node_modules` is not up to date.
=> Auto sync deps before running `pnpm` commands
